### ISSUE TITLE
[POGO] `LaunchTournament.py` fails out of a fresh install

### ISSUE THREAD

**Issue by xxbidiao** [StephenGss/PAL#14]
I'm using the instructions provided in branch `release_2.0`, but `LaunchTournament.py` failed to run. Did I do something wrong? Thanks!

```
$ python LaunchTournament.py 
2021-09-30_19:07:25: DEBUG: Game List created. 100 games read. 100 games will be played
2021-09-30_19:07:25: DEBUG: sorted games to be played: ['../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00000_I0020_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00001_I0103_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00002_I0242_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00003_I0097_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00004_I0099_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00005_I0145_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00006_I0139_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00007_I0052_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00008_I0055_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00009_I0112_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00010_I0250_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00011_I0155_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00012_I0071_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00013_I0019_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00014_I0085_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00015_I0028_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00016_I0037_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00017_I0005_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00018_I0007_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00019_I0114_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00020_I0092_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00021_I0194_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00022_I0033_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00023_I0198_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00024_I0118_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00025_I0269_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00026_I0299_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00027_I0181_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00028_I0182_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00029_I0004_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00030_I0191_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00031_I0120_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00032_I0018_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00033_I0004_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00034_I0027_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00035_I0265_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00036_I0037_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00037_I0034_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00038_I0102_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00039_I0151_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00040_I0029_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00041_I0107_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00042_I0152_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00043_I0042_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00044_I0089_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00045_I0159_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00046_I0240_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00047_I0234_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00048_I0131_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00049_I0206_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00050_I0148_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00051_I0019_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00052_I0158_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00053_I0144_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00054_I0024_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00055_I0054_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00056_I0224_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00057_I0244_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00058_I0025_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00059_I0165_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00060_I0061_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00061_I0212_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00062_I0023_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00063_I0082_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00064_I0048_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00065_I0069_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00066_I0066_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00067_I0027_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00068_I0192_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00069_I0157_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00070_I0171_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00071_I0052_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00072_I0052_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00073_I0162_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00074_I0198_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00075_I0173_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00076_I0196_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00077_I0231_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00078_I0141_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00079_I0236_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00080_I0042_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00081_I0263_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00082_I0155_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00083_I0272_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00084_I0061_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00085_I0251_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00086_I0281_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00087_I0271_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00088_I0115_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00089_I0207_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00090_I0287_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00091_I0292_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00092_I0264_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00093_I0240_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00094_I0031_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00095_I0204_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00096_I0035_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00097_I0151_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00098_I0228_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00099_I0036_N0.json']
2021-09-30_19:07:25: DEBUG: PAL command: gradlew  --stacktrace runclient
2021-09-30_19:07:25: DEBUG: PAL Client Initiated
2021-09-30_19:07:25: DEBUG: PAL Client ERROR. PAL Client Re-Initialized...
2021-09-30_19:07:25: DEBUG: PAL Client ERROR. PAL Client Re-Initialized...
2021-09-30_19:07:25: DEBUG: PAL Client ERROR. PAL Client Re-Initialized...
2021-09-30_19:07:25: DEBUG: PAL Client ERROR. PAL Client Re-Initialized...
2021-09-30_19:07:25: DEBUG: PAL Client ERROR. PAL Client Re-Initialized...
2021-09-30_19:07:25: DEBUG: PAL Client ERROR. PAL Client Re-Initialized...
2021-09-30_19:07:25: DEBUG: PAL Client ERROR. PAL Client Re-Initialized...
2021-09-30_19:07:25: DEBUG: PAL Client ERROR. PAL Client Re-Initialized...
2021-09-30_19:07:25: DEBUG: PAL Client ERROR. PAL Client Re-Initialized...
2021-09-30_19:07:25: DEBUG: PAL Client ERROR. PAL Client Re-Initialized...
2021-09-30_19:07:25: DEBUG: PAL Client ERROR. Game State Misalignment. Tournament Ending. What happened?
ERROR: ExitCode: 127
Traceback (most recent call last):
  File "LaunchTournament.py", line 847, in <module>
    pal.execute()
  File "LaunchTournament.py", line 508, in execute
    raise subprocess.CalledProcessError(exitCode, "")
subprocess.CalledProcessError: Command '' returned non-zero exit status 127.
Fatal Python error: could not acquire lock for <_io.BufferedWriter name='<stdout>'> at interpreter shutdown, possibly due to daemon threads
Python runtime state: finalizing (tstate=0x55ce9c2ed970)

Thread 0x00007f9ba27fc700 (most recent call first):
  File "LaunchTournament.py", line 247 in read_output
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 870 in run
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007f9ba2ffd700 (most recent call first):
  File "LaunchTournament.py", line 249 in read_output
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 870 in run
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007f9ba37fe700 (most recent call first):
  File "LaunchTournament.py", line 249 in read_output
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 870 in run
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007f9ba3fff700 (most recent call first):
  File "LaunchTournament.py", line 249 in read_output
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 870 in run
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007f9bc0bbe700 (most recent call first):
  File "LaunchTournament.py", line 249 in read_output
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 870 in run
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007f9bc13bf700 (most recent call first):
  File "LaunchTournament.py", line 249 in read_output
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 870 in run
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007f9bc1bc0700 (most recent call first):
  File "LaunchTournament.py", line 249 in read_output
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 870 in run
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007f9bc23c1700 (most recent call first):
  File "LaunchTournament.py", line 249 in read_output
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 870 in run
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007f9bc2bc2700 (most recent call first):
  File "LaunchTournament.py", line 249 in read_output
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 870 in run
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007f9bc33c3700 (most recent call first):
  File "LaunchTournament.py", line 249 in read_output
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 870 in run
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007f9bc3bc4700 (most recent call first):
  File "LaunchTournament.py", line 249 in read_output
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 870 in run
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/home/zhiyu/anaconda3/envs/pal_manager/lib/python3.8/threading.py", line 890 in _bootstrap

Current thread 0x00007f9bc652b180 (most recent call first):
<no Python frame>
Aborted (core dumped)

```

**Comment by StephenGss** [comment]
This is possibly a missing or wrong version java dependency.  Can you supply the PAL_log for that run attempt? It is located in PolycraftAIGym/Logs/[run-date]/

**Comment by xxbidiao** [comment]
Hi, Attached are my log files. Seems like `gradlew` missing is the culprit, meaning that you are correct. Do I just reinstall Java or should I do something else?

Debug log:

```
2021-09-30_19:07:25: DEBUG: Game List created. 100 games read. 100 games will be played
2021-09-30_19:07:25: DEBUG: sorted games to be played: ['../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00000_I0020_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00001_I0103_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00002_I0242_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00003_I0097_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00004_I0099_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00005_I0145_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00006_I0139_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00007_I0052_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00008_I0055_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00009_I0112_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00010_I0250_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00011_I0155_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00012_I0071_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00013_I0019_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00014_I0085_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00015_I0028_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00016_I0037_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00017_I0005_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00018_I0007_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00019_I0114_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00020_I0092_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00021_I0194_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00022_I0033_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00023_I0198_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00024_I0118_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00025_I0269_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00026_I0299_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00027_I0181_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00028_I0182_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00029_I0004_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00030_I0191_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00031_I0120_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00032_I0018_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00033_I0004_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00034_I0027_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00035_I0265_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00036_I0037_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00037_I0034_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00038_I0102_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00039_I0151_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00040_I0029_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00041_I0107_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00042_I0152_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00043_I0042_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00044_I0089_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00045_I0159_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00046_I0240_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00047_I0234_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00048_I0131_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00049_I0206_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00050_I0148_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00051_I0019_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00052_I0158_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00053_I0144_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00054_I0024_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00055_I0054_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00056_I0224_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00057_I0244_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00058_I0025_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00059_I0165_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00060_I0061_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00061_I0212_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00062_I0023_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00063_I0082_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00064_I0048_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00065_I0069_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00066_I0066_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00067_I0027_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00068_I0192_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00069_I0157_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00070_I0171_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00071_I0052_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00072_I0052_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00073_I0162_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00074_I0198_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00075_I0173_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00076_I0196_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00077_I0231_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00078_I0141_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00079_I0236_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00080_I0042_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00081_I0263_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00082_I0155_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00083_I0272_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00084_I0061_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00085_I0251_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00086_I0281_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00087_I0271_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00088_I0115_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00089_I0207_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00090_I0287_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00091_I0292_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00092_I0264_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00093_I0240_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00094_I0031_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00095_I0204_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00096_I0035_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00097_I0151_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00098_I0228_N0.json', '../pogo_100_PN/POGO_L00_T01_S01_X0100_U9999_V0_G00099_I0036_N0.json']
2021-09-30_19:07:25: DEBUG: PAL command: gradlew  --stacktrace runclient
2021-09-30_19:07:25: DEBUG: PAL Client Initiated
2021-09-30_19:07:25: DEBUG: PAL Client ERROR. PAL Client Re-Initialized...
2021-09-30_19:07:25: DEBUG: PAL Client ERROR. PAL Client Re-Initialized...
2021-09-30_19:07:25: DEBUG: PAL Client ERROR. PAL Client Re-Initialized...
2021-09-30_19:07:25: DEBUG: PAL Client ERROR. PAL Client Re-Initialized...
2021-09-30_19:07:25: DEBUG: PAL Client ERROR. PAL Client Re-Initialized...
2021-09-30_19:07:25: DEBUG: PAL Client ERROR. PAL Client Re-Initialized...
2021-09-30_19:07:25: DEBUG: PAL Client ERROR. PAL Client Re-Initialized...
2021-09-30_19:07:25: DEBUG: PAL Client ERROR. PAL Client Re-Initialized...
2021-09-30_19:07:25: DEBUG: PAL Client ERROR. PAL Client Re-Initialized...
2021-09-30_19:07:25: DEBUG: PAL Client ERROR. PAL Client Re-Initialized...
2021-09-30_19:07:25: DEBUG: PAL Client ERROR. Game State Misalignment. Tournament Ending. What happened?
```

PAL log:

```
2021-09-30_19:07:25: PAL: /bin/sh: 1: gradlew: not found

2021-09-30_19:07:25: PAL: /bin/sh: 1: gradlew: not found

2021-09-30_19:07:25: PAL: /bin/sh: 1: gradlew: not found

2021-09-30_19:07:25: PAL: /bin/sh: 1: gradlew: not found

2021-09-30_19:07:25: PAL: /bin/sh: 1: gradlew: not found

2021-09-30_19:07:25: PAL: /bin/sh: 1: gradlew: not found

2021-09-30_19:07:25: PAL: /bin/sh: 1: gradlew: not found

2021-09-30_19:07:25: PAL: /bin/sh: 1: gradlew: not found

2021-09-30_19:07:25: PAL: /bin/sh: 1: gradlew: not found

2021-09-30_19:07:25: PAL: /bin/sh: 1: gradlew: not found

2021-09-30_19:07:25: PAL: /bin/sh: 1: gradlew: not found
```
