### ISSUE TITLE
[POGO] rare? crash in PAL, different error than #45

### ISSUE THREAD

**Issue by musliner** [StephenGss/PAL#49]
logs avail on request; machine was 56% idle.

musliner@openmind0:~/openmind/code/test/results/pal-tournament-v2-shared-6-3-1-E-2022-01-07-103701-openmind0/openmind-in-polycraft-v2-domains-tournament-2022-01-07-103838-a0a51282ce0e

2022-01-07_16:40:17: PAL: [2022-01-07 10:40:15] [16:40:15] [TOURNAMENT MANAGER API THREAD/INFO]: [CLIENT TO TOUR MANAGER]{"goal":{"goalType":"ITEM","goalAchieved":true},"command_result":{"command":"RESET","argument":"domain /openmind/code/test/pal-game-configs/from-v2-shared-6-3-1-E/POGO_L06_T03_S01_X0100_E_U0015_V0_G00015_I0028_N1.json","result":"SUCCESS","message":"Attempting Reset","stepCost":0.0}}^M
^M
2022-01-07_16:40:17: PAL: [2022-01-07 10:40:15] [16:40:15] [Server thread/INFO]: Running Command on SERVER side: edu.utd.minecraft.mod.polycraft.aitools.commands.APICommandReset^M
^M
2022-01-07_16:40:17: PAL: [2022-01-07 10:40:15] [16:40:15] [Server thread/INFO]: [edu.utd.minecraft.mod.polycraft.privateproperty.network.AbstractBaseMessage:<init>:46]: Test^M
^M
2022-01-07_16:40:17: PAL: [2022-01-07 10:40:15] [16:40:15] [Server thread/INFO]: [edu.utd.minecraft.mod.polycraft.experiment.old.ExperimentManager:sendExperimentUpdates:322]: Sending Update...^M
^M
2022-01-07_16:40:17: PAL: [2022-01-07 10:40:15] [16:40:15] [Server thread/FATAL]: Error executing task^M
^M
2022-01-07_16:40:17: PAL: [2022-01-07 10:40:15] java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException^M
^M
2022-01-07_16:40:17: PAL: [2022-01-07 10:40:15]         at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_162]^M
^M
2022-01-07_16:40:17: PAL: [2022-01-07 10:40:15]         at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_162]^M
^M
2022-01-07_16:40:17: PAL: [2022-01-07 10:40:15]         at net.minecraft.util.Util.runTask(SourceFile:45) [Util.class:?]^M
^M
2022-01-07_16:40:17: PAL: [2022-01-07 10:40:15]         at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:660) [MinecraftServer.class:?]^M
^M
2022-01-07_16:40:17: PAL: [2022-01-07 10:40:15]         at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:605) [MinecraftServer.class:?]^M

**Comment by musliner** [comment]
this may be related to agent sending action command racing against game reset.. not sure.  I added a couple seconds delay after we/PAL realize we've made the POGO to give PAL some time to converge, and at least on two tests this didnt appear.

**Comment by musliner** [comment]
(there was already a similar delay in our agent after PAL announces game-over, but this issue occurred before that happened afaict)

**Comment by StephenGss** [comment]
I found the cause of this error. There was a line referencing our old experiment system that was causing the issue. 
I'll push an update with the fix.

**Comment by StephenGss** [comment]
This is fixed by commit 480052cf36b4c57deacfb097464f4d73e710b768
