### ISSUE TITLE
null pointer exceptions running shared novelty 9-1-1-H

### ISSUE THREAD

**Issue by mpatsift** [StephenGss/PAL#73]
PAL is consistently throwing null pointer exceptions when we run the 9-1-1-H shared novelty.  Here are three examples:

* pal-tournament-2022-10-12-104258-openmind0.log.gz

2022-10-12_15:46:15: PAL: [2022-10-12 10:46:15] [15:46:15] [BOT API THREAD/INFO]: [CLIENT]{"goal":{"goalType":"ITEM","goalAchieved":false,"Distribution":"Uninformed"},"command_result":{"command":"BREAK_BLOCK","argument":"","result":"SUCCESS","message":"","stepCost":3600.0},"step":58,"gameOver":false}

2022-10-12_15:46:15: PAL: [2022-10-12 10:46:15] [15:46:15] [BOT API THREAD/INFO]: [SCORE]step:59,totalCost:19096.135,totalReward:16000.0,adjustedReward:-3096.1348

2022-10-12_15:46:15: PAL: [2022-10-12 10:46:15] [15:46:15] [Server thread/ERROR]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@5d225fe7:

2022-10-12_15:46:15: PAL: [2022-10-12 10:46:15] java.lang.NullPointerException

2022-10-12_15:46:15: PAL: [2022-10-12 10:46:15] 	at edu.utd.minecraft.mod.polycraft.experiment.tutorial.TutorialFeatureEntity.moveTowardsTarget(TutorialFeatureEntity.java:447) ~[TutorialFeatureEntity.class:?]

* pal-tournament-2022-10-12-164936-openmind0.log.gz

2022-10-12_21:53:32: PAL: [2022-10-12 16:53:32] [21:53:32] [BOT API THREAD/INFO]: [CLIENT]{"goal":{"goalType":"ITEM","goalAchieved":false,"Distribution":"Uninformed"},"command_result":{"command":"BREAK_BLOCK","argument":"","result":"SUCCESS","message":"","stepCost":3600.0},"step":58,"gameOver":false}

2022-10-12_21:53:32: PAL: [2022-10-12 16:53:32] [21:53:32] [BOT API THREAD/INFO]: [SCORE]step:59,totalCost:19096.135,totalReward:16000.0,adjustedReward:-3096.1348

2022-10-12_21:53:32: PAL: [2022-10-12 16:53:32] [21:53:32] [Server thread/ERROR]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@6528cf87:

2022-10-12_21:53:32: PAL: [2022-10-12 16:53:32] java.lang.NullPointerException

2022-10-12_21:53:32: PAL: [2022-10-12 16:53:32] 	at edu.utd.minecraft.mod.polycraft.experiment.tutorial.TutorialFeatureEntity.moveTowardsTarget(TutorialFeatureEntity.java:447) ~[TutorialFeatureEntity.class:?]

* pal-tournament-2022-10-13-115127-openmind0.log.gz

2022-10-13_16:54:43: PAL: [2022-10-13 11:54:43] [16:54:43] [BOT API THREAD/INFO]: [CLIENT]{"goal":{"goalType":"ITEM","goalAchieved":false,"Distribution":"Uninformed"},"command_result":{"command":"TP_TO","argument":"68,17,73","result":"SUCCESS","message":"","stepCost":584.4646},"step":58,"gameOver":false}

2022-10-13_16:54:43: PAL: [2022-10-13 11:54:43] [16:54:43] [BOT API THREAD/INFO]: [SCORE]step:59,totalCost:15717.809,totalReward:16000.0,adjustedReward:282.1914

2022-10-13_16:54:43: PAL: [2022-10-13 11:54:43] [16:54:43] [Server thread/ERROR]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@42ecc94a:

2022-10-13_16:54:43: PAL: [2022-10-13 11:54:43] java.lang.NullPointerException

2022-10-13_16:54:43: PAL: [2022-10-13 11:54:43] 	at edu.utd.minecraft.mod.polycraft.experiment.tutorial.TutorialFeatureEntity.moveTowardsTarget(TutorialFeatureEntity.java:447) ~
[pal-tournament-2022-10-12-104258-openmind0.log](https://github.com/StephenGss/PAL/files/9810723/pal-tournament-2022-10-12-104258-openmind0.log)
[TutorialFeatureEntity.class:?]
[pal-tournament-2022-10-12-104258-openmind0.log.gz](https://github.com/StephenGss/PAL/files/9810725/pal-tournament-2022-10-12-104258-openmind0.log.gz)

[pal-tournament-2022-10-12-164936-openmind0.log.gz](https://github.com/StephenGss/PAL/files/9810727/pal-tournament-2022-10-12-164936-openmind0.log.gz)

**Comment by StephenGss** [comment]
Hi,

This has been fixed in 8da86be7a2da680f65cf80227007061f7014b3d4
The problem exists when there are no diamond blocks, but the pogoist tries to find them.

**Comment by mpatsift** [comment]
Passed a few times here.  Thanks!
