### ISSUE TITLE
[POGO] 10-1-1 shared novelties "Expecting property name enclosed in double quotes"

### ISSUE THREAD

**Issue by mpatsift** [StephenGss/PAL#76]
I'm seeing this sort of thing fairly often when running the 10-1-1 configs:
`2022-11-09_21:37:08: PAL: [2022-11-09 15:37:08] [21:37:08] [Server thread/INFO]: [edu.utd.minecraft.mod.polycraft.experiment.tutorial.TutorialFeatureTreeRot:onServerTickUpdate:131]:\
 block rotten *** BlockPos{x=91, y=17, z=60}^M
^M
Traceback (most recent call last):^M
  File "/openmind/code/test/LaunchTournament.py", line 847, in <module>^M
    pal.execute()^M
  File "/openmind/code/test/LaunchTournament.py", line 423, in execute^M
    if self._check_ended(str(next_line)):^M
  File "/openmind/code/test/LaunchTournament.py", line 206, in _check_ended^M
    data_dict = json.loads(json_text)^M
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads^M
    return _default_decoder.decode(s)^M
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode^M
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())^M
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode^M
    obj, end = self.scan_once(s, idx)^M
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)`

[pal-tournament-2022-11-09-153400-openmind0-mpelican.log.gz](https://github.com/StephenGss/PAL/files/9975652/pal-tournament-2022-11-09-153400-openmind0-mpelican.log.gz)

**Comment by StephenGss** [comment]
I think this was caused by a dubug message getting parsed by the Tournament launcher. I've removed the debug logs and pushed an update to the release_2.0 branch. (commit 4e3c4f5b159467357fd8206faf19ac1b8207c145)
